### ISSUE TITLE
[Editor] Touchbar Integration on macOS

### ISSUE THREAD

**Issue by suicvne** [WohlSoft/Moondust-Project#197]
Touchbar integration on the new 2016 MacBook Pros for PGE Editor!

I might be getting one soon and this would be a fun project to undergo I think. For those unaware, Apple recently replaced the function row on their 2016 MacBook Pros (13 inch and 15 inch) with a multitouch OLED strip known as the Touchbar. It's contextually aware on a per app basis depending on if the app integrates it.

![Example](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/Art/touchbar_hero_2x.png)

Here's an interesting "cheat sheet" or set of examples Wohl found when we discussed it on Discord that I'm linking for reference:
https://github.com/loretoparisi/touchbar

```
Wohlstand: 
I think, I would try to deal with something, and PGE Editor would have something for that
buttons like "exit", "open", "new level", new world map, new script, save, save-as, do test, etc.
```
Just some example actions to add later.

**Comment by Wohlstand** [comment]
I think, I will try to implement that after I will finish works on **engine-qstring-to-stdstring** branch (to porting PGE Engine into pure STL+SDL2), this things must be very useful!

**Comment by suicvne** [comment]
I slept on it and thought of a pretty neat idea for it: section switching. Push a section switch button which lets you scroll through all the sections and boom you can go right to it. can't wait to play around with this integration!

**Comment by Wohlstand** [comment]
I have found this sample https://github.com/msorvig/qt-touchbar when I have remembered something...

**Comment by Wohlstand** [comment]
As we discussed with @suicvne at Discord, we decided to close this task as it has no future Apple burred down the touch bar concept and started to produce new models of MacBook Pro with classic F keys. Mainly, because people in most wasn't found this idea being useful and preferred to have the classic F keys in a more well-known and intuitive way.
