### ISSUE TITLE
Animate NPC flipping left and right when direction is set to random

### ISSUE THREAD

**Issue by The0x539** [WohlSoft/Moondust-Project#223]

**Comment by Alucard648** [comment]
This will help distingush NPC`s with this setting on at glance in the editor.

**Comment by Wohlstand** [comment]
For disabled animation is meta-sign (transparent two-way arrow) would be better (like generator arrows)

**Comment by The0x539** [comment]
Yes, that would work.

**Comment by Wohlstand** [comment]
Instead of this, NPC will get a meta-sign that NPC has a randmized direction:
![изображение](https://github.com/WohlSoft/Moondust-Project/assets/6751442/6c244a5f-639f-4c18-a9a2-27972e03b71d)
So, I'll close this.
