### ISSUE TITLE
More editor metatags

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/Moondust-Project#234]
- [x] Exclamation mark above talkative friendly NPC`s. Complete with message string showing on hovering on that "!" sign.

- [x] Blue or cyan shading on slippery blocks.

Sorry for necroposting.

**Comment by Wohlstand** [comment]
That easy to add, and I think to add that into re-organized version, I'll keep this in my mind.

It's not a necroposting 😉

**Comment by Wohlstand** [comment]
Completed just now!

**Comment by Wohlstand** [comment]
What's done:
![Снимок экрана от 2023-11-24 05-14-21](https://github.com/WohlSoft/Moondust-Project/assets/6751442/064f0379-af64-44f3-80dd-176e4f67be3d)
![Снимок экрана от 2023-11-24 05-02-44](https://github.com/WohlSoft/Moondust-Project/assets/6751442/3c130731-1ae3-42a6-a734-dd374855e56b)
![Снимок экрана от 2023-11-24 04-37-46](https://github.com/WohlSoft/Moondust-Project/assets/6751442/ed3e1ca4-ebc6-45c7-9985-f48e3ff5c2c5)
