### ISSUE TITLE
More typos discovered in English and Russian translations

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/Moondust-Project#274]
**Which component?**
- Component name Editor
- Version of it; latest build

**Describe the bug**
Ran raw translation file through Notepad++ plugin called [Aspell](http://aspell.net/), and it discovered many typoes in English and Russian translation files

**To Reproduce**
Here are instructions on how to install Aspell plugin for Notepad++ 
https://habr.com/post/184400/

Here is complete brakdown of all typoes found by spell checker. Typoed words are marked with square brackets in list.

- [x] Properties box will not be shown [atomatically] when you select an item to place,
like when choosing an item from the item toolbox or from the tileset item box.

- [ ] [Crytical] 
Критические ошибки

- [x] Этот конфигурационный пакет не содержит [настроечую] утилиту.

- [x] Папки [конфигуркции:]

- [x] World map: [Terrian] tiles

- [x] Since the last crash, the editor [recorved] some files.
Please save them first before doing anything else.

- [x] [Terrian] tile //Встречается несколько раз в файле.

- [x] [В разработке] Попытка протестировать [уровено] в редакторе SMBX!

- [x] Сбрасывает необработанное исключение, чтобы [спрврцировать] аварию редактора

- [x] Классический [интрерфейс] более похож на редактор старого движка

- [x] [Стуктут] //Встречается несколько раз в файле.

- [x] [Извинте], но слот события

- [x] [Рразрешить] предметы

- [x] Message limits: max line [lenth] is 28 characters

- [ ] Input directory [wich] contains the SMBX GIF files

- [x] Это [консолная] утилита, которая исправляет лениво сделанные маски, [созданые] для SMBX.

- [x] [Откыть] исходную папку

- [x] [Посколькоу] конфигурации объектов не загружены.
//Встречается несколько раз в файле.

- [x] Пожалуйста, [ввездите] название уровня для

- [x] [Подалуйста], удалите лишние Блоки с [уровеня]  или [сохрание] файл в формат LVLX.
//Опечатки, подобные этим встречается несколько раз в файле.

- [x] >На этом уровне имеются некоторые неправильные файлы конфигураций, которые не могут загрузиться. Чтобы это сообщение не появлялось в следующий раз, пожалуйста, исправьте следующие ошибки в ваших [кофигурационных] файлах в пользовательских папках:

- [ ] [Termiates] frozen thread to allow you to run a test again.
LunaLUA test loader thread is busy, try again or try [termiate] frozen loader!

- [x] Запустить тест уровня в устаревшем движке.
Чтобы эта возможность работала, [треубется] наличие последней версии LunaLua.
Иначе, эта возможность будет работать очень ограниченно.

- [x] Позволяет запускать уровни очень быстро после [превого] запуска.

- [ ] [Terminite] frozen LunaTester on the attempt to send any command to LunaLua.

- [ ] Violation of SMBX64 standard has [beeen] found!

- [ ] SMBX Test is already runned //running

- [ ] Fail to send file [patth] into LunaDLL:

- [x] [Прерзвать] запущенный процесс

- [x] [Извинте], но слот события &quot;Стукнут&quot; уже используется событием

- [x] [Источик] //Используется в диалоге клонирования секций.

- [ ] [Destiation]//Используется там же.

- [x] Пожалуйста, [выберие] другую секцию
или удалите эту секцию с помощью свойства
//Встречается несколько раз в файле.

- [ ] [Horisontal] speed:

- [ ] [Copyed] Event// Copied //Встречается несколько раз.

- [x] Message limits: max line [lenth] is 28 characters //Встречается несколько раз.

- [ ] Hited: //Hit

- [x] Содержимое [конейнера] НИП

- [x] [Поикс] польз. фон.об.

- [x] Changed [Warpsetting]

- [x] Changed [Eventsetting]

- [x] Changed [Sectionsetting]

- [x] Changed [Levelsetting]

- [ ] Not [Moveable] //Movable

- [ ] Event Block [Hited] //Hit

- [x] [Соедининение] левого-правого крёв

- [ ] Wrap [horizontaly]//horizontally

- [ ] Wrap [vertucally]

- [x] Править [пользоватьский] конфиг фона...

- [x] Сначала нужно [выберать] фоновую картинку

- [x] Только [Спц-Сост]

- [x] Разрешить [проходитть] через этот проход с обеих сторон.

- [x] Как быстро будет лететь игрок в момент [вылетета].

- [x] [Выбр]//Не знаю, где используется.

- [x] Удалить текущую запись [прохда] вместе со всеми размещёнными точками.

- [ ] Please, put this level file with a world map, or create new world map in the same [fomder] with this level file.

- [x] [Аттрибуты] //Атрибуты 

- [ ] have [diffirence] words

- [x] [Совмеренный] интерфейс

- [x] Глобальный сценарий для всех уровней [эпизона]. //Встречается несколько раз.

- [x] Начальное [приветсвие]

- [ ] Global level [scrupt] for entire episode.

- [x] Сбросить [мастшаб]

- [ ] Clear NPC [garbadge]... //garbage

- [ ] Open a custom folder: a folder with a name equal to the [basen ame] of the currently opened file.

- [x] Вкл. граф. исправление ([требутеся] переоткрыть файл

- [x] [Заклазки] позиции. Сохраняют текущую позицию камеры. Вы можете использовать их, чтобы быстро вернуться в нужное место на большой карте.

- [x] Этот флаг включает альтернативный [алогритм] применения маски чтобы корректно отобразить лениво-сделанную графику

- [ ] [Eriser]

- [x] Содержимое [конейнера] нИП

- [ ] [Horisontal] speed: //Again.

- [x] [Показть] сообщение:

- [ ] [Pattles] and tilesets //Palettes

- [x] [Кооридоный] мир (Без карты мира)

- [x] Чтобы начать работу с [новоу] конфигурацией, пожалуйста, перезапустите приложение.

- [ ] Please, put this level file with a world map, or create new world map in the same [fomder] with this level file.

- [ ] Sorry, the World Maps support is not [inplemented] in this version.

- [x] Извините, [поддерка] карт мира пока не реализована в этой версии приложения.

- [x] Невозможно начать тестирование, т.к. движок не найден: 
Пожалуйста, [проверье] папку приложения.

- [ ] [Vanilia] SMBX detected!// Vanilla. Используется несколько раз.

- [x] Вы имеете устаревшую сборку SMBX (Vanilia)!
Это значит, что с данной сборкой невозможно автоматически запустить тестовый уровень. 
Чтобы запустить тест [урвоня] вручную, запустите SMBX в режиме игры и зайдите в эпизод
// Используется несколько раз.

- [x] Движок PGE - это находящийся в разработке компонент PGE Project, который реализует игровой процесс и функциональность [тестирвоания] уровней.

- [x] Это значит, что автозапуск теста уровня невозможен. Чтобы запустить тест уровня, будет сгенерирован временный эпизод, [которвый] вы можете запустить и выбрать вручную.

- [ ] Fail to send file [patth] into LunaDLL:

- [x] Движок уже тестирует другой [уровеньl].
Пожалуйста, выйдите из движка и попробуйте ещё раз.

- [ ] {Clonning] of section...

- [ ] Section has been [clonned]

- [x] Файл не использует [пользовательску графикую].

- [ ] Already [exsist] // Используется несколько раз.

- [x] Конфигурационный пакет загружен с ошибками.
[Пожауйста], откройте Инструменты/Глобальная Конфигурация/Состояние текущей конфигурации
чтобы получить [подробнуюю] информацию.

- [ ] Everything is fine, level has no NPC [gargabe]! //"gargabe" Встречается несколько раз в файле перевода.

- [ ] If you [contunue] this operation, application can be frozen.

- [x] НИПы [можгут] стоять сверху

- [ ] [Modyfied] //Modified

- [ ] sorry, but PGE has crashed. Reason: Out of memory! :(
To prevent this, try closing other [uneccessary] programs to free up more memory. //unnecessary

- [x] Чтобы [недопустить] этого, пожалуйста, закройте ненужные программы чтобы освободить больше памяти. //Надо раздельно

- [x] [Сылка] форума: wohlsoft.ru/forum

- [ ] {Invizible] //Invisible

- [ ] Not [Moveable] //Movable

- [x] [Рразрешить] предметы

- [x] [Соедининение] левого-правого крёв

- [x] [Корридорный] мир //Встречается несколько раз

- [ ] Editor was [abourted] because alarm() time out!

- [ ] Editor was [abourted] because physical memory error!

- [x] [Зfгрузка] изображений путей...

- [x] Во время сохранения уровня в формат SMBX64 [проихошли] неполадки: //Встречается несколько раз

- [x] Инициализация категорий [Хэлементых] наборов... //Элементных 

- [x] Не [сохраять] 

- [ ] [Detele] this tileset

- [x] [Пожалкйста], введите имя файла!

- [x] [Неудалось] загрузить набор плиток! //Раздельно 

- [x] Это редактор глобальных наборов.
Все наборы элементов, сделанные здесь, будут сохранены в этой папке:

Т.е. все сохранённые наборы будут глобальны для [конфируационного] пакета и могут быть использованы в групповых наборах.

Если вы желаете создать локальный набор для [уровеня]/мира с использованием собственной графики, пожалуйста, откройте &quot;Набор элементов&quot; и найдите кнопку

- [x] [Пожалкйста], введите имя файла!

- [ ] [Previouse] tip

- [x] Слой уже [сщуествует]

- [ ] Crystal [Sphare] Exit

- [x] Финишная [леточка]

- [x] Замечание: Используйте колёсико мыши для прокрутки по карте. Вы можете прокрутить горизонтально вместе с зажатой [клвавижей] ALT на клавиатуре.

- [x] >Замечание: Используйте колёсико мыши для прокрутки по карте. Вы можете прокрутить горизонтально вместе с зажатой [клвавижей] CTRL на клавиатуре.

- [x] Невозможно открыть файл 
[Посколькоу] конфигурации объектов не загружены.
// Подобная опечатка встречается несколько раз.

- [x] Точка не [выбрата] // выбрана 

- [x] [Измененена] настройка объекта

- [ ] Applying [Leves]...

- [x] Расширение файла не [определно], пожалуйста, введите расширение файла!

- [x] {Подалуйста], удалите лишние Плитки с карты мира или {сохрание] файл в формат WLDX.
// Подобная опечатка встречается несколько раз.

- [ ] This is a console tool which convert the SMBX graphics which have a gif format with [transparence] mask into PNG format with own transparence.

- [ ] Input directory [wich] contains the SMBX GIF files

- [x] [Откыть] исходную папку

---
Some typoes can duplicate multiple times in translation. Use find/replace to fix them all.

**Comment by Wohlstand** [comment]
![default](https://user-images.githubusercontent.com/6751442/47260962-e3cc4780-d4cd-11e8-905f-1af29d2eca9b.png)
Where the "vanished" type means translation is obsolete / outdated, and... it's a trash! So, I'll nuke this so incorrect string into the trash :wastebasket: :fox_face:

**Comment by Wohlstand** [comment]
![default](https://user-images.githubusercontent.com/6751442/47261021-eda27a80-d4ce-11e8-9345-f307862464f3.png)
This one typo is epic :rofl: :man_facepalming:

**Comment by Wohlstand** [comment]
> Лучше "Только Спец-Сост".
Сделано! :wink: 

![default](https://user-images.githubusercontent.com/6751442/47261091-b92fbe00-d4d0-11e8-8b24-810adb331278.png)
Эпизон? т.е. "Epi-Zone": Тут же вспомнил "эпицентр" и представился полигон для ядерных испытаний :rofl:

**Comment by Wohlstand** [comment]
> Сбросить [мастшаб]

С этой опечатки поржал как "must shab".

**Comment by Wohlstand** [comment]
> [Выбр]//Не знаю, где используется.

Это тут:
![default](https://user-images.githubusercontent.com/6751442/47261137-f6e11680-d4d1-11e8-8078-27c54acb803b.png)

Сделал сокращённо, а так, поправлю на "выбрать", ибо после серии обновлений уже нет смысла сокращать здесь...

**Comment by Wohlstand** [comment]
> Извините, [поддерка] карт мира пока не реализована в этой версии приложения.

Историческая надпись... Вчера как раз рыл содержимое найденных образов мёртвых виртуалок 2013-го года, столько там нашёл различных древностей... Этой надписи уже давно нет в переводе, и в самом приложении тоже :fox_face:

**Comment by Wohlstand** [comment]
> Файл не использует [пользовательску графикую].

Эта опечатка породила новый глагол: "графиковать" :rofl:

**Comment by Wohlstand** [comment]
> Чтобы [недопустить] этого, пожалуйста, закройте ненужные программы чтобы освободить больше памяти. //Надо раздельно

Двойка мне по русскому за "Слитон-Раздельно"  :-P

**Comment by Wohlstand** [comment]
>  [Корридорный] мир //Встречается несколько раз

Это уже не опечатка, а я не правильно написал слово...

**Comment by Wohlstand** [comment]
> Инициализация категорий [Хэлементых] наборов... //Элементных

Почему-то вспомнил "Люди Хэ", которых мне недавно показал друг... :rofl:
Глянул, "Хэ" у меня не было, но посмеялся от души, однако, исправил

**Comment by Wohlstand** [comment]
> Точка не [выбрата] // выбрана

Почему-то эта опечатка ассоциируется у меня с "выбрита"... "Точка не выбрита", ну верно, это ведь не голова, и тем более не армия! :smiley:

**Comment by Wohlstand** [comment]
Закрываю эту тему, потому что она уже серьёзно устарела.

Любые исправления можно внести через WebLate сразу: https://hosted.weblate.org/projects/moondust-project/
