### ISSUE TITLE
[Editor] A quicker way to toggle grid align sizes via the [ and ] keys

### ISSUE THREAD

**Issue by FireSeraphim** [WohlSoft/Moondust-Project#381]
**Is your feature request related to a problem? Please describe.**
I would appreciate a quicker way to toggle grid align sizes since as of late I find myself doing it a lot when I'm level designing and having to constantly go to edit menu and change it, then change it back when I'm done gets kinda tedious after a while.
**Describe the solution you'd like**
I would appreciate it if PGE had the [ and ] keys as quick keyboard shortcuts for the set align grid size command, with each press of the [ or ] incrementing the align grid size and having the \ key to set the align grid size back to the default setting. Having a quick set of key binds for setting the align grid size would cut down on the tedium and the amount of time I have to take to toggle them
**Describe alternatives you've considered**
I'm afraid I haven't really though of any.

**Comment by FireSeraphim** [comment]
I'm still waiting for this feature. What's taking so long?

**Comment by FireSeraphim** [comment]
Still waiting for this... would be really nice if this suddenly appeared the next build of the moondust editor/pge

**Comment by Wohlstand** [comment]
A good reminder, I'll try to add in the next few days, hot-keys were not hard to make, or I'll try to make these hotkeys now, I'll only need to make the loop that will toggle between different grid sizes. I am right now busy with other cases, and I am not at home in these weeks, and so, getting tired when I am at home. However, I am still keep planning and the development around. ~~You may join my Discord server to see everything and get all latest news from the first source~~ Oh, you were already here, welcome! :fox_face:

**Comment by Wohlstand** [comment]
Whoops, forgot to close this issue, the task has been completed a while ago...
