### ISSUE TITLE
[Moondust Editor] I keep starting with a boot equipped on player 1

### ISSUE THREAD

**Issue by FireSeraphim** [WohlSoft/Moondust-Project#441]
**Which component?**
Level Editor (Version e18bdff-Master)

**Describe the bug**
I'm running into a rather bizarre glitch where at first when I test the level via for first time the default powerup state is fine, then when I test the level via Lunatester subsequently it keeps giving Player 1 a boot. It even affect the testing setting menu.

**To Reproduce**
1. Test once via LunaTester
2. and then test again via LunaTester

**Expected behavior**
I suspect something got borked somewhere on the config side of things or something to that effect

**Screenshots**
<img src="https://i.ibb.co/s3D8ZVq/2021-07-09-00-31-12.png" alt="2021-07-09-00-31-12" border="0">
an example of this bizarre bug in action

**Comment by Wohlstand** [comment]
I guess, there is a small glitch with the data returning,  when you change some in the game, that gets returned back into Editor and Editor reminds that changed state. Recently I had to update that mechanism to make TheXTech is able to feedback player states, changed star number, and return properties for taken item by magic hand, etc. The LunaTester receives such feedback data by a different way that can't hurt this, but I'll try to check what happen here 🤔

**Comment by Wohlstand** [comment]
Just in a case, open the Test menu and the Test settings menu item, and please check what the startup state is requested here?

**Comment by FireSeraphim** [comment]
<a href="https://ibb.co/d2K1jcm"><img src="https://i.ibb.co/vPzgVBX/Screen-Shot-005.png" alt="Screen-Shot-005" border="0"></a>

**Comment by Wohlstand** [comment]
This literally means the shoe is attached:
![изображение](https://user-images.githubusercontent.com/6751442/125082232-a40b7b00-e0cf-11eb-80d6-377cb0bed84c.png)

Try to switch off this (set into [no vehicle]), and try the game again

**Comment by FireSeraphim** [comment]
I did. I should mention that after the first time you close SMBX and then test twice again it resets back to giving the player a boot, even in the testing menu. Really strange...

**Comment by Wohlstand** [comment]
Okay, I did the check, and I confirm that is the bug: the vehicle type gets taken from off the player's state, so, if you would be a fire-powered, you'll get Yoshi :smirk_cat:

**Comment by Wohlstand** [comment]
Fixed, please test

**Comment by FireSeraphim** [comment]
It seems to have been resolved. I think it would be a good idea though to get another person to test this as well and verify.

**Comment by Wohlstand** [comment]
This bug is really small and dumb, you can see the code change I made to fix it, so, as you confirm, I'll close this. So, if somebody will get the same bug, simply tell to run the Devkit update

**Comment by Wohlstand** [comment]
Closed as resolved

**Comment by FireSeraphim** [comment]
I was just now testing my level a second time after launching and testing my level the first time and well once again it seems the bug won't stay dead.
![Screen Shot 006](https://user-images.githubusercontent.com/39662230/125169827-8b53a180-e171-11eb-9167-6135cbc5424f.PNG)

**Comment by Wohlstand** [comment]
> Reply to deleted post

That the state was left from your last test that left the buggy state. So, the problem was:
- Editor to SMBX2 - was fine, your current test settings from Editor should appear at SMBX2 as was set
- SMBX2 to Editor - here was a bug, there was a mess that caused vehicle type and ID to be set by the same value as player's state ID. that was dumb:
```
arr[1] - player character (1 - Mario)
arr[2] - player state (1 - small)
arr[3] - vehicle type (0 - none, 1 - shoe, 2 - clown car, 3 - Yoshi)
arr[4] - vehicle state (colour of a shoe or Yoshi)
```
the bug was because I set the value of `arr[2]` into vehicle type and vehicle id, and once I fixed that, it should work

**Comment by Wohlstand** [comment]
EDIT: That looks like you still have the old version of Editor, please check the Help/About to find which build date you do have, it should be from today.
