### ISSUE TITLE
[Musplay] Make wav-Recordings have Settings added to the Filename

### ISSUE THREAD

**Issue by 0lhi** [WohlSoft/Moondust-Project#461]
**Is your feature request related to a problem? Please describe.**
By default, the Musplay Recordings to not carry any information on how these recordings came to be. This makes it hard to remember settings worth considering, and to distinguish the recorded files from each other.

**Describe the solution you'd like**
Have .wav filenames include the settings that lead to the sound output (for example, a recording of a MIDI file using the ADL Device with the _AIL (Death Gate)_ bank would be saved as **SONGNAME-mid-s0-b33.wav**). This would also make it easier to share the results with others, who then can give their opinions.

**Describe alternatives you've considered**
Edit the filenames manually. But with so many options available, that's not very feasible.

**Additional context**
\-

**Comment by Wohlstand** [comment]
Feature is done here: https://github.com/WohlSoft/Moondust-Project/commit/0478a2c2f207c6e8841b8ddc48de10299b32d9d4

Please tes the work.

**Comment by 0lhi** [comment]
- MIDI ADL works
- MIDI OPN works
- MIDI FluidSynth works
- NES Tracks work

Test successful! =)

**Comment by Wohlstand** [comment]
So, I'll close this, task completed!
