### ISSUE TITLE
[Enhancement] - Improved Roto Disc Options

### ISSUE THREAD

**Issue by ChristianSilvermoon** [WohlSoft/Moondust-Project#504]
**Is your feature request related to a problem? Please describe.**
Everbody's favorite Disco Waffles only seem to do their classical circular pattern from SMB3...

But in [Mario Forever (Video with specific time linked)](https://youtu.be/EfH9-X1w8K0?t=1949)

They jam out in some more... *interesting* patterns.

**Describe the solution you'd like**
I think it would be really neat if we could choose between:
* Circle (classic)
* Flower (Mario Forever)
* Lemniscate (Like this ∞)

As well as control their speed

EDIT: I'm silly, this is the wrong Repo, my apologies >.<

**Comment by Wohlstand** [comment]
Then I'll transfer

**Comment by ChristianSilvermoon** [comment]
> ~Then I'll transfer~
> 
> Damn, can't transfer between WohlSoft organization and my personal account

I had already copy/pasted it anyhow over at [TheXTech's Issue #358](https://github.com/Wohlstand/TheXTech/issues/358) ^^
