### ISSUE TITLE
Open Level folder and Open Episode Folder commands stopped working

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/Moondust-Project#513]
**Which component?**
Editor - Build date 18 Aug 2022
 
**Describe the bug**
File ->Open Level folder and File-> Open Episode Folder menu commands cease to open level`s respective folders in Windows Explorer.

**To Reproduce**
1. Open a level with custom data in editor.
2. File ->Open Level folder.
3. No effect.

**Expected behavior**
A folder caontaining level should open in case of calling File-> Open Episode Folder and folder containing custom data used by level in case of calling File ->Open Level folder should be opened in Windows Explorer.

**Screenshots**
Not much to say.

**Desktop specs (please complete the following information):**
Windows 10

**Comment by Wohlstand** [comment]
Okay, I made a fix that should work now. The reason for this is my attempt to fix the double-slash at path begin on UNIX-like operating systems, but, this broke work on Windows. So, I applied to use of the universal solution that should work everywhere normally without of ugly workarounds.

**Comment by Alucard648** [comment]
Fix works like magic.
