### ISSUE TITLE
Wrong file extension returned by Level.filename() when testing SMBX2 in editor

### ISSUE THREAD

**Issue by Emral** [WohlSoft/Moondust-Project#520]
**Which component?**
- Editor
- Since upgrade to d635482 we talked about in another thread

**Describe the bug**
Before: Level.filename() prints .lvlx or .lvl extension
Now: Level.filename() prints .x extension (BAD)

**To Reproduce**
1. Open editor and a smbx2 level
2. Open console with tab
3. Type Level.filename() and hit enter
4. levelname.x

**Expected behavior**
4. levelname.lvlx

**Screenshots**
![image](https://user-images.githubusercontent.com/4628923/192158931-6fc11928-1f05-4ed1-a4ed-ceb47a935ebb.png)

![image](https://user-images.githubusercontent.com/4628923/192158942-3ec69a70-faea-4ce4-999e-2fb93cd1747c.png)

**Comment by Wohlstand** [comment]
Seems a very small bug, lemme me check some...

**Comment by Wohlstand** [comment]
@Emral, fixed just now, please verify the latest build once it gets built (see "Actions" tab)
