### ISSUE TITLE
ability to get musicboxes' indexes in the editor

### ISSUE THREAD

**Issue by krazybluemonkey** [WohlSoft/Moondust-Project#540]
As the title says, some way to get a musicboxes' index. Plenty of other objects have the ability, so i feel it'd be at home. Possibly as a context/right-click menu item.

**Comment by Wohlstand** [comment]
Do you mean the ID of music entry that was set,  or their order in array?

**Comment by krazybluemonkey** [comment]
order in the array. i thought index/indices was synonymous enough, sorry

**Comment by Wohlstand** [comment]
I added the "Copy properties" menu item:
<https://github.com/WohlSoft/Moondust-Project/commit/18b5141c5857aa3da82463f81d1ad75ac1a17187>
So, should be fine now.

**Comment by Wohlstand** [comment]
@krazybluemonkey, please test the result.

**Comment by Wohlstand** [comment]
Auto-closed during no reply for a while.
