### ISSUE TITLE
Editor: "Reload config pack" silently crashes the editor

### ISSUE THREAD

**Issue by Emral** [WohlSoft/Moondust-Project#576]
**Which component?**
![image](https://github.com/WohlSoft/Moondust-Project/assets/4628923/c3f7e051-b384-4271-8bd4-c77dafbd57da)

**Describe the bug**
Hitting "Reload Config Pack" causes the editor to close. Test environment: Current dev build of SMBX2.

**Crash report and log files**
Critical: Config data path not exists: ../data/

**Desktop specs (please complete the following information):**
 - Win 11

My only lead is that it might have to do with this:
![image](https://github.com/WohlSoft/Moondust-Project/assets/4628923/3aff65ea-3379-42f7-a327-a1a5e96c6d63)

Prior to me updating the editor today, it was simply ..
I had to change it because SMBX2 wouldn't open, producing this log:

Critical: Level graphics path not exists: C:/X2/graphics/
Fatal: Initialization failure: Error loading configuration package

Adding a / at the end doesn't change the result.

**Comment by Wohlstand** [comment]
I guess, I accdentally messed something here: https://github.com/WohlSoft/Moondust-Project/commit/cb71cb1bc16fece0ccc16948fcaf20afb35713f6
Yeah, I missed up some of code while made this freature, going to fix this as fast as spossible.

**Comment by Wohlstand** [comment]
Okay, I fixed the bug just now. Please wait until the CI build completes https://github.com/WohlSoft/Moondust-Project/actions/runs/5363707359, and then:
- Revert the update to "main.ini".
- Perform the update of the DevKit again.

**Comment by Emral** [comment]
Fixed, thanks!
