### ISSUE TITLE
JSON options for WLDX?

### ISSUE THREAD

**Issue by LoveBodhi** [WohlSoft/Moondust-Project#583]
For example: I would set "Episode Type" as "Classic" and "Wonder" in Nostalgic Paradise asset (TheXTech).

**Comment by ds-sloth** [comment]
This is a great idea; we need to think some internally about how "different asset packs for the same engine" should work before we implement it.

If you're thinking about custom JSON metadata that the engine can read, I think this is already supported by Moondust but not used by TheXTech. Wohlstand can confirm whether this is the case.

**Comment by LoveBodhi** [comment]
>we need to think some internally about how "different asset packs for the same engine" should work before we implement it.

I think is the **Riivolution-like options** best for it?
