### ISSUE TITLE
Editor doesn't obey kubuntu theme

### ISSUE THREAD

**Issue by Shadowblitz16** [WohlSoft/Moondust-Project#594]
**Is your feature request related to a problem? Please describe.**
The editor doesn't seem to try to use my os's style
![image](https://github.com/WohlSoft/Moondust-Project/assets/2453707/07db5841-6a11-4a59-9916-df41f37346c4)

**Describe the solution you'd like**
Please support native theming.

**Describe alternatives you've considered**
Idk

**Comment by Wohlstand** [comment]
Sounds like, you need to build the whole devkit from the source using system-wide installed Qt rather than using prebuilt thing: it uses limited number of features to be able work on a wide number of systems.

**Comment by Wohlstand** [comment]
Also: Pre-built Devkit gets built with minimal set to support as much distros as possible, so, it may won't handle system-wide themes. So, you should build the devkit from the source code using system-wide Qt toolchain that has full integration to KDE.

**Comment by SkullGamer205** [comment]
> The editor doesn't seem to try to use my os's style

Rebuild Moondust Devkit with `system-libs`

Like this:
```
cd <MoondustKit_Dir>
git pull (or git clone https://github.com/WohlSoft/Moondust-Project <MoondustKit_Dir>)
git submodule init
git submodule update
./build.sh clean
./build.sh ninja deploy system-libs
```

**Comment by Shadowblitz16** [comment]
@SkullGamer205 
```
shadowblitz16@Kubuntu:~/Documents/Source/c/Moondust-Project$ ./build.sh clean
./build.sh ninja deploy system-libs
======== Remove all cached object files and automatically generated Makefiles ========
removing Dependencies build cache ...
==== Clear! ====
/home/shadowblitz16/Documents/Source/c/Moondust-Project
==RELEASE BUILD!==
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
--- DEBUG: Source of branch: ---
    OVERRIDE_GIT_BRANCH=
    PULL_REQUEST_NUMBER=
    SEMAPHORE_GIT_BRANCH=
    APPVEYOR_REPO_BRANCH=
    APPVEYOR_PULL_REQUEST_NUMBER=
    TRAVIS_BRANCH=
    TRAVIS_PULL_REQUEST=
--------------------------------
== Current GIT hash [200d0d91f], branch [master], package [master] ==
== Qt has been found in /usr/lib/x86_64-linux-gnu/cmake/Qt5
-- Found /usr/bin/lrelease, locales will be compiled!
-- Found /usr/bin/lupdate, locales can be refreshed!
-- Finding Qt component: Qt5Core
-- Finding Qt component: Qt5Gui
-- Finding Qt component: Qt5Widgets
-- Finding Qt component: Qt5Network
-- Finding Qt component: Qt5Concurrent
-- Finding Qt component: Qt5Qml
CMake Error at _common/library_qt.cmake:79 (find_package):
  By not providing "FindQt5Qml.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Qml", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Qml" with any
  of the following names:

    Qt5QmlConfig.cmake
    qt5qml-config.cmake

  Add the installation prefix of "Qt5Qml" to CMAKE_PREFIX_PATH or set
  "Qt5Qml_DIR" to a directory containing one of the above files.  If "Qt5Qml"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  _common/library_qt.cmake:92 (pge_qt_find_and_define_lib)
  CMakeLists.txt:30 (include)


-- Configuring incomplete, errors occurred!
See also "/home/shadowblitz16/Documents/Source/c/Moondust-Project/build-pge-cmake-release/CMakeFiles/CMakeOutput.log".

```

**Comment by Wohlstand** [comment]
@Shadowblitz16, Please install next:
```bash
sudo apt-get install qt5-qmake qttools5-dev qttools5-dev-tools libqt5gui5 libqt5core5a libqt5widgets5 libqt5concurrent5 libqt5qml5 qtdeclarative5-dev libqt5network5 qt5-image-formats-plugins qt5-gtk-platformtheme qt5dxcb-plugin qtwayland5 libqt5waylandclient5
```
and re-run the build as @SkullGamer205 tells.

**Comment by Shadowblitz16** [comment]
How do I install it now?

**Comment by Wohlstand** [comment]
> How do I install it now?

Just copy the whole text in the box, and run it in the terminal: sudo apt-get install <anything-also>.

**Comment by Shadowblitz16** [comment]
What box? ```
PGE_Project/calibrator/spriteconf/mario-4.ini
PGE_Project/calibrator/spriteconf/link-5.ini
PGE_Project/calibrator/spriteconf/toad-4.ini
PGE_Project/calibrator/spriteconf/peach-4.ini
PGE_Project/calibrator/spriteconf/luigi-2.ini
PGE_Project/calibrator/spriteconf/peach-3.ini
PGE_Project/calibrator/spriteconf/toad-1.ini
PGE_Project/pge_editor
PGE_Project/PNG2GIFs
PGE_Project/libFreeImageLite.so
PGE_Project/changelog.musplay.txt
PGE_Project/ipc
PGE_Project/ipc/LunaLoader-exec.exe
PGE_Project/ipc/38a_ipc_bridge.exe
PGE_Project/ipc/luna_hwnd_show.exe
=== OK! ===


=====================Passed time: 0h 2m 30s=====================
=============================BUILT!=============================
Press any key to continue...
shadowblitz16@Kubuntu:~/Documents/Source/c/Moondust-Project$ sudo apt-get install .
[sudo] password for shadowblitz16: 
Reading package lists... Done
E: Unsupported file . given on commandline
shadowblitz16@Kubuntu:~/Documents/Source/c/Moondust-Project$ sudo apt-get install ./
Reading package lists... Done
E: Unsupported file ./ given on commandline
shadowblitz16@Kubuntu:~/Documents/Source/c/Moondust-Project$ sudo apt-get install .
Reading package lists... Done
E: Unsupported file . given on commandline

```

**Comment by Wohlstand** [comment]
> =====================Passed time: 0h 2m 30s=====================
> =============================BUILT!=============================

Sounds like, you already built the Devkit completely, all stuff following these lines, makes no sense.

**Comment by Wohlstand** [comment]
> What box?

The block with a text inside, shown in THIS message: https://github.com/WohlSoft/Moondust-Project/issues/594#issuecomment-1913706295

**Comment by Shadowblitz16** [comment]
> > What box?
> 
> The block with a text inside, shown in THIS message: [#594 (comment)](https://github.com/WohlSoft/Moondust-Project/issues/594#issuecomment-1913706295)

Oh sorry for the confusion I did already built it but I don't see it in my app menu.

**Comment by Wohlstand** [comment]
> Oh sorry for the confusion I did already built it but I don't see it in my app menu.

It won't appear in the app menu until you manually create all Desktop files that links to built binaries.

**Comment by Wohlstand** [comment]
Closing as completed, me and @Shadowblitz16 completely solved the problem: it's need to just build the project from the source code and link to system-installed Qt libraries, so, result is:
![изображение](https://github.com/WohlSoft/Moondust-Project/assets/6751442/fc55a2bb-6db0-46b1-809d-c4ae0ae81543)
